require('dotenv').config();
const { getCollection } = require('../src/db/dbClient');

const sampleProperties = [
	{
		house_id: '_x31__Lawns1',
		text: ['1'],
		x: 3479.58,
		y: 1190.17,
		element: {},
		title: '1 Bedroom Studio - Lawns',
		description: 'A compact and modern 1 bedroom studio, perfect for city living...',
		type: 'STUDIO',
		section: 'STUDIO',
		status: 'RESERVED',
		price: 175000,
		bedrooms: 1,
		bathrooms: 1,
		squareFootage: 500,
		features: ['Integrated appliances', 'Walk-in shower', 'City skyline view', 'Secure entry'],
		imageUrl: '/images/lawns-studio.jpg',
	},
	{
		house_id: '_x32__Lawns2',
		text: ['2'],
		x: 3650.23,
		y: 1210.45,
		element: {},
		title: '2 Bedroom Apartment - Lawns',
		description: 'A stylish 2-bedroom apartment offering modern living with ample space.',
		type: 'APARTMENT',
		section: 'APARTMENT',
		status: 'AVAILABLE',
		price: 290000,
		bedrooms: 2,
		bathrooms: 2,
		squareFootage: 800,
		features: ['Open-plan kitchen', 'Balcony', 'City skyline view', 'Gym access'],
		imageUrl: '/images/lawns-2bed.jpg',
	},
	{
		house_id: '_x33__Lawns3',
		text: ['3'],
		x: 3802.89,
		y: 1305.67,
		element: {},
		title: 'Luxury Penthouse - Lawns',
		description: 'A breathtaking penthouse with floor-to-ceiling windows and premium amenities.',
		type: 'PENTHOUSE',
		section: 'PENTHOUSE',
		status: 'SOLD',
		price: 950000,
		bedrooms: 3,
		bathrooms: 3,
		squareFootage: 1800,
		features: ['Private terrace', 'Smart home system', 'Underground parking', '24/7 security'],
		imageUrl: '/images/lawns-penthouse.jpg',
	},
	{
		house_id: '_x34__Meadow1',
		text: ['4'],
		x: 2550.45,
		y: 1100.78,
		element: {},
		title: 'Countryside Cottage - Meadow',
		description: 'A charming cottage nestled in the peaceful countryside, ideal for relaxation.',
		type: 'HOUSE',
		section: 'HOUSE',
		status: 'FOR SALE',
		price: 350000,
		bedrooms: 3,
		bathrooms: 2,
		squareFootage: 1600,
		features: ['Fireplace', 'Large garden', 'Scenic views', 'Private driveway'],
		imageUrl: '/images/meadow-cottage.jpg',
	},
	{
		house_id: '_x35__Meadow2',
		text: ['5'],
		x: 2605.78,
		y: 1152.34,
		element: {},
		title: 'Modern Townhouse - Meadow',
		description: 'A stylish townhouse with high-end finishes and a contemporary design.',
		type: 'TOWNHOUSE',
		section: 'TOWNHOUSE',
		status: 'RESERVED',
		price: 475000,
		bedrooms: 3,
		bathrooms: 3,
		squareFootage: 2200,
		features: ['Garage', 'Open-plan kitchen', 'Smart home technology', 'Community park access'],
		imageUrl: '/images/meadow-townhouse.jpg',
	},
	{
		house_id: '_x36__Meadow3',
		text: ['6'],
		x: 2700.65,
		y: 1189.78,
		element: {},
		title: 'Family Home - Meadow',
		description: 'A spacious 4-bedroom family home with a large backyard and great amenities.',
		type: 'HOUSE',
		section: 'HOUSE',
		status: 'AVAILABLE',
		price: 520000,
		bedrooms: 4,
		bathrooms: 3,
		squareFootage: 2800,
		features: ['Backyard', 'Garage', 'Open living space', 'Hardwood floors'],
		imageUrl: '/images/meadow-familyhome.jpg',
	},
	{
		house_id: '_x37__Harbor1',
		text: ['7'],
		x: 3100.12,
		y: 1400.89,
		element: {},
		title: 'Waterfront Villa - Harbor',
		description: 'A luxurious waterfront villa with direct ocean access and breathtaking views.',
		type: 'VILLA',
		section: 'VILLA',
		status: 'FOR SALE',
		price: 1250000,
		bedrooms: 5,
		bathrooms: 4,
		squareFootage: 4500,
		features: ['Private dock', 'Infinity pool', 'Ocean view', 'Gated community'],
		imageUrl: '/images/harbor-villa.jpg',
	},
	{
		house_id: '_x38__Harbor2',
		text: ['8'],
		x: 3205.45,
		y: 1452.12,
		element: {},
		title: 'Luxury Condo - Harbor',
		description: 'A high-end condo with resort-style amenities and spectacular city views.',
		type: 'CONDO',
		section: 'CONDO',
		status: 'RESERVED',
		price: 600000,
		bedrooms: 2,
		bathrooms: 2,
		squareFootage: 1400,
		features: ['Rooftop pool', 'Fitness center', 'Concierge service', 'Secure parking'],
		imageUrl: '/images/harbor-condo.jpg',
	},
	{
		house_id: '_x39__Harbor3',
		text: ['9'],
		x: 3350.78,
		y: 1500.34,
		element: {},
		title: 'Downtown Loft - Harbor',
		description: 'A trendy loft in the heart of downtown, perfect for young professionals.',
		type: 'APARTMENT',
		section: 'APARTMENT',
		status: 'FOR RENT',
		price: 2800,
		bedrooms: 1,
		bathrooms: 1,
		squareFootage: 900,
		features: ['Industrial design', 'High ceilings', 'Exposed brick', 'City views'],
		imageUrl: '/images/harbor-loft.jpg',
	},
	{
		house_id: '_x40__Greenview1',
		text: ['10'],
		x: 2805.23,
		y: 1250.78,
		element: {},
		title: 'Eco-Friendly Smart Home - Greenview',
		description: 'A sustainable home with cutting-edge smart features and energy efficiency.',
		type: 'HOUSE',
		section: 'HOUSE',
		status: 'AVAILABLE',
		price: 700000,
		bedrooms: 4,
		bathrooms: 3,
		squareFootage: 2500,
		features: ['Solar panels', 'Smart thermostat', 'Rainwater harvesting', 'Energy-efficient appliances'],
		imageUrl: '/images/greenview-smart.jpg',
	},
];

async function seedDatabase() {
	try {
		const collection = await getCollection(process.env.COSMOS_DB_COLLECTION);

		// Check if data already exists
		const count = await collection.countDocuments();
		if (count > 0) {
			console.log(`Database already contains ${count} properties. Skipping seed.`);
			process.exit(0);
		}

		// Insert sample data
		const result = await collection.insertMany(sampleProperties);
		console.log(`Successfully seeded database with ${result.insertedCount} properties`);
		process.exit(0);
	} catch (error) {
		console.error('Error seeding database:', error);
		process.exit(1);
	}
}

seedDatabase();
