name: Build and deploy Node.js app to Azure Web App - glenveagh-api

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  # Backend job - Azure App Service deployment
  backend_job:
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    name: Backend Build and Deploy
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: npm install, build, and test
        run: |
          cd server  # Change to your server directory
          npm install
          npm run build --if-present
          npm run test --if-present
      
      - name: Zip artifact for deployment
        run: |
          cd server  # Change to your server directory
          zip -r ../server-release.zip ./*
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: server-release.zip
  
  # Backend deployment job        
  backend_deploy:
    runs-on: ubuntu-latest
    needs: backend_job
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Unzip artifact for deployment
        run: unzip server-release.zip -d server
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2F541A70E259479EA19378F58537D3C6 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AC404C2E35F24A6A88FFB4814B9C3F6A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0544C928871341F28E51505AE0AD49ED }}
      
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'glenveagh-api'
          slot-name: 'Production'
          package: ./server
